class Temple {
	public static void main(String[] args)
	{
		String temple1="Tirupati"; 
		String temple2="Dharmasthala"; 
		String temple3="Kukke"; 
		String temple4="Murudeshwar";
		String temple5="Meenakshi"; 
		String temple6="Golden Temple"; 
		String temple7="Somnath"; 
		String temple8="Kedarnath";
		String temple9="Badrinath"; 
		String temple10="Rameshwaram"; 
		String temple11="Jagannath"; 
		String temple12="Vaishno Devi";
		String temple13="Padmanabha"; 
		String temple14="Shirdi"; 
		String temple15="Iskcon"; 
		String temple16="Chamundi";
		String temple17="Kashi"; 
		String temple18="Akshardham"; 
		String temple19="Mahakal"; 
		String temple20="Dwarka";
		String temple21="Virupaksha"; 
		String temple22="Hampi"; 
		String temple23="Chidambaram"; 
		String temple24="Sabarimala";
		String temple25="Udupi"; 
		String temple26="Lingaraj"; 
		String temple27="Brihadeeswara"; 
		String temple28="Belur";
		String temple29="Halebidu"; 
		String temple30="Guruvayur"; 
		String temple31="Kanchi"; 
		String temple32="Annamalai";
		String temple33="Raghavendra"; 
		String temple34="Yellamma"; 
		String temple35="Banashankari"; 
		String temple36="Nanjangud";
		String temple37="Talakadu"; 
		String temple38="Sringeri"; 
		String temple39="Kateel"; 
		String temple40="Kollur";
		String temple41="Kolaramma"; 
		String temple42="Mahalakshmi"; 
		String temple43="Kalighat"; 
		String temple44="Dakshineswar";
		String temple45="Birla"; 
		String temple46="ISKCON BLR"; 
		String temple47="Shani"; 
		String temple48="Trimbak";
		String temple49="Omkareshwar"; 
		String temple50="Amarnath";
		String[] temples={temple1,temple2,temple3,temple4,temple5,temple6,temple7,temple8,temple9,temple10,temple11,temple12,temple13,temple14,temple15,
		                  temple16,temple17,temple18,temple19,temple20,temple21,temple22,temple23,temple24,temple25,temple26,temple27,temple28,temple29,temple30,
		                  temple31,temple32,temple33,temple34,temple35,temple36,temple37,temple38,temple39,temple40,temple41,temple42,temple43,temple44,temple45,
		                  temple46,temple47,temple48,temple49,temple50};
		System.out.println("Total temples : "+temples.length);
		System.out.println("Temple 1 :"+temples[0]);
		System.out.println("Temple 2 :"+temples[1]);
		System.out.println("Temple 3 :"+temples[2]);
		System.out.println("Temple 4 :"+temples[3]);
		System.out.println("Temple 5 :"+temples[4]);
		System.out.println("Temple 6 :"+temples[5]);
		System.out.println("Temple 7 :"+temples[6]);
		System.out.println("Temple 8 :"+temples[7]);
		System.out.println("Temple 9 :"+temples[8]);
		System.out.println("Temple 10 :"+temples[9]);
		System.out.println("Temple 11 :"+temples[10]);
		System.out.println("Temple 12 :"+temples[11]);
		System.out.println("Temple 13 :"+temples[12]);
		System.out.println("Temple 14 :"+temples[13]);
		System.out.println("Temple 15 :"+temples[14]);
		System.out.println("Temple 16 :"+temples[15]);
		System.out.println("Temple 17 :"+temples[16]);
		System.out.println("Temple 18 :"+temples[17]);
		System.out.println("Temple 19 :"+temples[18]);
		System.out.println("Temple 20 :"+temples[19]);
		System.out.println("Temple 21 :"+temples[20]);
		System.out.println("Temple 22 :"+temples[21]);
		System.out.println("Temple 23 :"+temples[22]);
		System.out.println("Temple 24 :"+temples[23]);
		System.out.println("Temple 25 :"+temples[24]);
		System.out.println("Temple 26 :"+temples[25]);
		System.out.println("Temple 27 :"+temples[26]);
		System.out.println("Temple 28 :"+temples[27]);
		System.out.println("Temple 29 :"+temples[28]);
		System.out.println("Temple 30 :"+temples[29]);
		System.out.println("Temple 31 :"+temples[30]);
		System.out.println("Temple 32 :"+temples[31]);
		System.out.println("Temple 33 :"+temples[32]);
		System.out.println("Temple 34 :"+temples[33]);
		System.out.println("Temple 35 :"+temples[34]);
		System.out.println("Temple 36 :"+temples[35]);
		System.out.println("Temple 37 :"+temples[36]);
		System.out.println("Temple 38 :"+temples[37]);
		System.out.println("Temple 39 :"+temples[38]);
		System.out.println("Temple 40 :"+temples[39]);
		System.out.println("Temple 41 :"+temples[40]);
		System.out.println("Temple 42 :"+temples[41]);
		System.out.println("Temple 43 :"+temples[42]);
		System.out.println("Temple 44 :"+temples[43]);
		System.out.println("Temple 45 :"+temples[44]);
		System.out.println("Temple 46 :"+temples[45]);
		System.out.println("Temple 47 :"+temples[46]);
		System.out.println("Temple 48 :"+temples[47]);
		System.out.println("Temple 49 :"+temples[48]);
		System.out.println("Temple 50 :"+temples[49]);
	}
}