class Tree{
	public static void main(String[] values)
	{
		String tree1 = "Neem";
		String tree2 = "Mango";
		String tree3 = "Banyan";
		String tree4 = "Peepal";
		String tree5 = "Coconut";
		String tree6 = "Palm";
		String tree7 = "Oak";
		String tree8 = "Pine";
		String tree9 = "Teak";
		String tree10 = "Eucalyptus";
		String tree11 = "Guava";
		String tree12 = "Banana";
		String tree13 = "Cherry";
		String tree14 = "Apple";
		String tree15 = "Orange";
		String tree16 = "Lemon";
		String tree17 = "Papaya";
		String tree18 = "Fig";
		String tree19 = "Ashoka";
		String tree20 = "Rosewood";
		String tree21 = "Willow";
		String tree22 = "Maple";
		String tree23 = "Cedar";
		String tree24 = "Spruce";
		String tree25 = "Fir";
		String[] treeNames = {tree1 , tree2 , tree3 , tree4 , tree5 , tree6 , tree7 , tree8 , tree9 , tree10 , tree11 , tree12 , tree13 , tree14 , tree15 , tree16 , tree17 , tree18 , tree19 , tree20 , tree21 , tree22 , tree23 , tree24 , tree25};
		int size = treeNames.length;
		System.out.println("Total number of trees : "+size);
		String name1 = treeNames[0];
		String name2 = treeNames[1];
		String name3 = treeNames[2];
		String name4 = treeNames[3];
		String name5 = treeNames[4];
		String name6 = treeNames[5];
		String name7 = treeNames[6];
		String name8 = treeNames[7];
		String name9 = treeNames[8];
		String name10 = treeNames[9];
		String name11 = treeNames[10];
		String name12 = treeNames[11];
		String name13 = treeNames[12];
		String name14 = treeNames[13];
		String name15 = treeNames[14];
		String name16 = treeNames[15];
		String name17 = treeNames[16];
		String name18 = treeNames[17];
		String name19 = treeNames[18];
		String name20 = treeNames[19];
		String name21 = treeNames[20];
		String name22 = treeNames[21];
		String name23 = treeNames[22];
		String name24 = treeNames[23];
		String name25 = treeNames[24];
		System.out.println("Tree 1 :"+name1);
		System.out.println("Tree 2 :"+name2);
		System.out.println("Tree 3 :"+name3);
		System.out.println("Tree 4 :"+name4);
		System.out.println("Tree 5 :"+name5);
		System.out.println("Tree 6 :"+name6);
		System.out.println("Tree 7 :"+name7);
		System.out.println("Tree 8 :"+name8);
		System.out.println("Tree 9 :"+name9);
		System.out.println("Tree 10 :"+name10);
		System.out.println("Tree 11 :"+name11);
		System.out.println("Tree 12 :"+name12);
		System.out.println("Tree 13 :"+name13);
		System.out.println("Tree 14 :"+name14);
		System.out.println("Tree 15 :"+name15);
		System.out.println("Tree 16 :"+name16);
		System.out.println("Tree 17 :"+name17);
		System.out.println("Tree 18 :"+name18);
		System.out.println("Tree 19 :"+name19);
		System.out.println("Tree 20 :"+name20);
		System.out.println("Tree 21 :"+name21);
		System.out.println("Tree 22 :"+name22);
		System.out.println("Tree 23 :"+name23);
		System.out.println("Tree 24 :"+name24);
		System.out.println("Tree 25 :"+name25);
	}
}